#!/usr/bin/env python3
"""Generate deterministic RGB565 launcher icons for the LapSight UserDemo app."""

from __future__ import annotations

from math import hypot
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
ASSET_DIR = ROOT / "main" / "apps" / "app_lapsight" / "assets"


def rgb565(red: int, green: int, blue: int) -> int:
    return ((red & 0xF8) << 8) | ((green & 0xFC) << 3) | (blue >> 3)


BACKGROUND = rgb565(28, 34, 47)
TRACK_DARK = rgb565(22, 109, 147)
TRACK_LIGHT = rgb565(66, 224, 245)
WHITE = rgb565(244, 248, 255)
ORANGE = rgb565(255, 151, 55)


def icon_pixels(size: int) -> list[int]:
    pixels = [BACKGROUND] * (size * size)

    def put(x: int, y: int, color: int) -> None:
        if 0 <= x < size and 0 <= y < size:
            pixels[y * size + x] = color

    center_x = (size - 1) / 2
    center_y = (size - 1) / 2
    outer_x = size * 0.40
    outer_y = size * 0.29

    for y in range(size):
        for x in range(size):
            normalized = hypot((x - center_x) / outer_x, (y - center_y) / outer_y)
            if 0.77 <= normalized <= 1.04:
                put(x, y, TRACK_LIGHT if y < center_y else TRACK_DARK)

    # A crisp L in the center keeps the icon recognizable at 40 x 40.
    stroke = max(2, size // 11)
    l_left = int(size * 0.39)
    l_top = int(size * 0.28)
    l_bottom = int(size * 0.67)
    l_right = int(size * 0.62)
    for y in range(l_top, l_bottom + 1):
        for x in range(l_left, l_left + stroke):
            put(x, y, WHITE)
    for y in range(l_bottom - stroke + 1, l_bottom + 1):
        for x in range(l_left, l_right + 1):
            put(x, y, WHITE)

    # Start/finish checker at the lower-right edge of the circuit.
    cell = max(2, size // 16)
    flag_x = int(size * 0.70)
    flag_y = int(size * 0.58)
    for row in range(3):
        for column in range(2):
            color = WHITE if (row + column) % 2 == 0 else ORANGE
            for y in range(flag_y + row * cell, flag_y + (row + 1) * cell):
                for x in range(flag_x + column * cell, flag_x + (column + 1) * cell):
                    put(x, y, color)

    return pixels


def write_header(name: str, size: int) -> None:
    values = icon_pixels(size)
    lines = [
        "/*",
        " * SPDX-FileCopyrightText: 2026 LapSight contributors",
        " *",
        " * SPDX-License-Identifier: MIT",
        " *",
        " * Generated by tools/generate_lapsight_icons.py; do not edit by hand.",
        " */",
        "#pragma once",
        "#include <stdint.h>",
        "",
        f"static const uint16_t image_data_lapsight_{name}[{size * size}] = {{",
    ]
    for start in range(0, len(values), 12):
        chunk = values[start : start + 12]
        lines.append("    " + ", ".join(f"0x{value:04x}" for value in chunk) + ",")
    lines.extend(["};", ""])
    (ASSET_DIR / f"lapsight_{name}.h").write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    ASSET_DIR.mkdir(parents=True, exist_ok=True)
    write_header("small", 40)
    write_header("big", 56)


if __name__ == "__main__":
    main()
