package com.huanfuli.lapsight.shared.ui

import androidx.compose.runtime.Composable
import androidx.compose.runtime.CompositionLocalProvider
import androidx.compose.runtime.ReadOnlyComposable
import androidx.compose.runtime.staticCompositionLocalOf
import com.huanfuli.lapsight.shared.LanguageMode
import com.huanfuli.lapsight.shared.systemLanguageTag
import com.huanfuli.lapsight.shared.track.CourseTopology

internal enum class AppLanguage {
    English,
    Chinese,
    Korean,
    Japanese,
    French,
    Spanish,
}

internal fun resolveAppLanguage(
    mode: LanguageMode,
    systemTag: String,
): AppLanguage = when (mode) {
    LanguageMode.System -> matchSystemLanguage(systemTag)
    LanguageMode.English -> AppLanguage.English
    LanguageMode.Chinese -> AppLanguage.Chinese
    LanguageMode.Korean -> AppLanguage.Korean
    LanguageMode.Japanese -> AppLanguage.Japanese
    LanguageMode.French -> AppLanguage.French
    LanguageMode.Spanish -> AppLanguage.Spanish
}

private fun matchSystemLanguage(systemTag: String): AppLanguage {
    val language = systemTag.trim().lowercase()
        .substringBefore('-')
        .substringBefore('_')
    return when (language) {
        "zh" -> AppLanguage.Chinese
        "ko" -> AppLanguage.Korean
        "ja" -> AppLanguage.Japanese
        "fr" -> AppLanguage.French
        "es" -> AppLanguage.Spanish
        else -> AppLanguage.English
    }
}

internal class LocalizedStrings(
    val language: AppLanguage,
    val drive: String,
    val review: String,
    val settings: String,
    val units: String,
    val locationSource: String,
    val phoneGps: String,
    val simulated: String,
    val locationLockedWhileTiming: String,
    val phoneGpsUnavailable: String,
    val phoneGpsPermissionRequired: String,
    val highRateGnss: String,
    val highRateGnssSupporting: String,
    val externalGnss: String,
    val externalGnssUnvalidatedNote: String,
    val theme: String,
    val themeSystem: String,
    val themeDark: String,
    val themeLight: String,
    val languageTitle: String,
    val languageSystem: String,
    val glasses: String,
    val registerPair: String,
    val castToGlasses: String,
    val glassesReconnecting: String,
    val glassesPage: String,
    val glassesOff: String,
    val hudDeltaOnly: String,
    val hudFocused: String,
    val hudTelemetry: String,
    val noGlassesDevices: String,
    val noGlassesSelected: String,
    val displayCapable: String,
    val displayUnsupported: String,
    val firmwareUpdateRequired: String,
    val glassesAppUpdateRequired: String,
    val openFirmwareUpdate: String,
    val openGlassesAppUpdate: String,
    val glassesIdle: String,
    val glassesConnecting: String,
    val glassesConnected: String,
    val whileTiming: String,
    val fullscreenWhileTiming: String,
    val keepScreenAwakeWhileTiming: String,
    val dashReadouts: String,
    val speedTrace: String,
    val gpsDiagnostics: String,
    val safetySettings: String,
    val sessions: String,
    val tracks: String,
    val rawCaptures: String,
    val archivedTracks: String,
    val noSavedSessionsYet: String,
    val emptyReviewText: String,
    val best: String,
    val sessionEntry: String,
    val trackEntry: String,
    val rawCaptureEntry: String,
    val untitled: String,
    val unfinishedSessionFound: String,
    val unfinishedSessionText: String,
    val discardUnfinishedTitle: String,
    val discardUnfinishedText: String,
    val resume: String,
    val save: String,
    val saveSession: String,
    val savingSession: String,
    val discard: String,
    val discardSession: String,
    val tapAgainDiscardSession: String,
    val cancel: String,
    val close: String,
    val checkSelectedTrack: String,
    val stillUseThisTrack: String,
    val chooseAnotherTrack: String,
    val sessionEnded: String,
    val sessionSaved: String,
    val startTiming: String,
    val stopTiming: String,
    val stopMarking: String,
    val stopRawRecording: String,
    val recordRawGpsDiagnostic: String,
    val rawGpsRecordingShort: String,
    val rawGpsRecordingLong: String,
    val markingGuidance: String,
    val waitingForFirstGpsFix: String,
    val markingTime: String,
    val points: String,
    val chooseTrack: String,
    val newTrack: String,
    val noTrackSelected: String,
    val pickSavedTrack: String,
    val markFirstTrack: String,
    val noSavedTracksYet: String,
    val track: String,
    val current: String,
    val needsStartFinishBeforeTiming: String,
    val direction: String,
    val courseType: String,
    val circuit: String,
    val pointToPoint: String,
    val recorded: String,
    val reverse: String,
    val switchToLandscape: String,
    val switchToPortrait: String,
    val closeTrackPicker: String,
    val trackReview: String,
    val reRecordTrack: String,
    val reRecordTrackTitle: String,
    val reRecordTrackText: String,
    val trackName: String,
    val retry: String,
    val discardTrack: String,
    val discardTrackTitle: String,
    val discardTrackText: String,
    val saveTrack: String,
    val cleanLoopsCaptured: String,
    val startFinishSet: String,
    val savingPlacesStartFinish: String,
    val failedCaptureStatus: String,
    val noLapTimesYet: String,
    val noLapTimesNote: String,
    val captureDetails: String,
    val loops: String,
    val detected: String,
    val accepted: String,
    val rejected: String,
    val samples: String,
    val degraded: String,
    val phoneGpsLive: String,
    val demoSimGps: String,
    val replay: String,
    val pauseReplay: String,
    val restartReplay: String,
    val exportJson: String,
    val exportGpx: String,
    val archive: String,
    val archived: String,
    val restore: String,
    val delete: String,
    val deleteReviewItemText: String,
    val rename: String,
    val duplicate: String,
    val edit: String,
    val setCurrent: String,
    val sectorTiming: String,
    val readyToSave: String,
    val tapTraceToPlaceStartFinish: String,
    val cancelEditing: String,
) {
    fun languageModeLabel(mode: LanguageMode): String = when (mode) {
        LanguageMode.System -> languageSystem
        LanguageMode.English -> "English"
        LanguageMode.Chinese -> "中文"
        LanguageMode.Korean -> "한국어"
        LanguageMode.Japanese -> "日本語"
        LanguageMode.French -> "Français"
        LanguageMode.Spanish -> "Español"
    }

    fun lapsRecordedSaveOrDiscard(laps: Int): String = when (language) {
        AppLanguage.English -> "Laps recorded: $laps. Save this run to Review, or discard it."
        AppLanguage.Chinese -> "已记录圈数：$laps。保存到回顾，或丢弃本次计时。"
        AppLanguage.Korean -> "기록된 랩: $laps. 이 주행을 리뷰에 저장하거나 폐기하세요."
        AppLanguage.Japanese -> "記録済みラップ: $laps。レビューに保存するか破棄します。"
        AppLanguage.French -> "Tours enregistrés : $laps. Enregistrez cette session dans Review ou supprimez-la."
        AppLanguage.Spanish -> "Vueltas registradas: $laps. Guarda esta sesión en Review o descártala."
    }

    fun lapsRecordedTapDiscard(laps: Int): String = when (language) {
        AppLanguage.English -> "Laps recorded: $laps. Tap discard again to permanently delete this session."
        AppLanguage.Chinese -> "已记录圈数：$laps。再次点按丢弃将永久删除本次计时。"
        AppLanguage.Korean -> "기록된 랩: $laps. 폐기를 다시 누르면 이 세션이 영구 삭제됩니다."
        AppLanguage.Japanese -> "記録済みラップ: $laps。もう一度破棄するとこのセッションを完全に削除します。"
        AppLanguage.French -> "Tours enregistrés : $laps. Touchez à nouveau supprimer pour effacer définitivement cette session."
        AppLanguage.Spanish -> "Vueltas registradas: $laps. Toca descartar otra vez para borrar esta sesión definitivamente."
    }

    fun revisionAndSectors(revision: Int, sectorCount: Int): String = when (language) {
        AppLanguage.English -> buildRevisionAndSectors("Rev", revision, "sectors", sectorCount)
        AppLanguage.Chinese -> buildRevisionAndSectors("版本", revision, "分段", sectorCount)
        AppLanguage.Korean -> buildRevisionAndSectors("리비전", revision, "섹터", sectorCount)
        AppLanguage.Japanese -> buildRevisionAndSectors("リビジョン", revision, "セクター", sectorCount)
        AppLanguage.French -> buildRevisionAndSectors("Rév.", revision, "secteurs", sectorCount)
        AppLanguage.Spanish -> buildRevisionAndSectors("Rev.", revision, "sectores", sectorCount)
    }

    fun markingGuidanceFor(topology: CourseTopology): String = when (language) {
        AppLanguage.English -> when (topology) {
            CourseTopology.Circuit -> "Record one complete lap, then stop marking. Extra laps only improve smoothing."
            CourseTopology.PointToPoint -> "Record one pass from start to finish, then stop marking."
        }
        AppLanguage.Chinese -> when (topology) {
            CourseTopology.Circuit -> "完整记录一圈后即可停止标记；多跑几圈只会让地图更平滑。"
            CourseTopology.PointToPoint -> "从起点到终点完整记录一次，然后停止标记。"
        }
        AppLanguage.Korean -> when (topology) {
            CourseTopology.Circuit -> "한 바퀴를 완전히 기록한 뒤 마킹을 중지하세요. 추가 랩은 지도 평활화만 개선합니다."
            CourseTopology.PointToPoint -> "출발점부터 도착점까지 한 번 기록한 뒤 마킹을 중지하세요."
        }
        AppLanguage.Japanese -> when (topology) {
            CourseTopology.Circuit -> "1周を完全に記録したらマーキングを停止できます。追加周回は地図の平滑化だけを改善します。"
            CourseTopology.PointToPoint -> "スタートからフィニッシュまで1回記録したらマーキングを停止してください。"
        }
        AppLanguage.French -> when (topology) {
            CourseTopology.Circuit -> "Enregistrez un tour complet, puis arrêtez le marquage. Les tours en plus ne servent qu'a lisser la carte."
            CourseTopology.PointToPoint -> "Enregistrez un passage du départ a l'arrivée, puis arrêtez le marquage."
        }
        AppLanguage.Spanish -> when (topology) {
            CourseTopology.Circuit -> "Registra una vuelta completa y luego detén el marcado. Las vueltas extra solo suavizan el mapa."
            CourseTopology.PointToPoint -> "Registra una pasada desde la salida hasta la meta y luego detén el marcado."
        }
    }

    fun failedCaptureStatusFor(topology: CourseTopology): String = when (language) {
        AppLanguage.English -> when (topology) {
            CourseTopology.Circuit -> "Couldn't build the course. Re-record one complete lap; extra laps are optional for smoother mapping."
            CourseTopology.PointToPoint -> "Couldn't build the open course. Re-record one clear start-to-finish pass."
        }
        AppLanguage.Chinese -> when (topology) {
            CourseTopology.Circuit -> "无法生成赛道。请重新完整记录一圈；多跑几圈只是为了让地图更平滑。"
            CourseTopology.PointToPoint -> "无法生成开放赛道。请重新记录一次清晰的起点到终点轨迹。"
        }
        AppLanguage.Korean -> when (topology) {
            CourseTopology.Circuit -> "코스를 만들 수 없습니다. 한 바퀴를 다시 완전히 기록하세요. 추가 랩은 선택 사항입니다."
            CourseTopology.PointToPoint -> "오픈 코스를 만들 수 없습니다. 출발점부터 도착점까지 한 번 선명하게 다시 기록하세요."
        }
        AppLanguage.Japanese -> when (topology) {
            CourseTopology.Circuit -> "コースを作成できませんでした。1周を完全に再記録してください。追加周回は任意です。"
            CourseTopology.PointToPoint -> "オープンコースを作成できませんでした。スタートからフィニッシュまで明確に1回再記録してください。"
        }
        AppLanguage.French -> when (topology) {
            CourseTopology.Circuit -> "Impossible de construire le parcours. Réenregistrez un tour complet; les tours en plus sont optionnels."
            CourseTopology.PointToPoint -> "Impossible de construire le parcours ouvert. Réenregistrez un passage clair du départ a l'arrivée."
        }
        AppLanguage.Spanish -> when (topology) {
            CourseTopology.Circuit -> "No se pudo crear el recorrido. Vuelve a registrar una vuelta completa; las vueltas extra son opcionales."
            CourseTopology.PointToPoint -> "No se pudo crear el recorrido abierto. Vuelve a registrar una pasada clara de salida a meta."
        }
    }

    private fun buildRevisionAndSectors(
        revisionLabel: String,
        revision: Int,
        sectorsLabel: String,
        sectorCount: Int,
    ): String = buildString {
        append("$revisionLabel $revision")
        if (sectorCount > 0) append(" · ${sectorCount + 1} $sectorsLabel")
    }
}

internal val LocalStrings = staticCompositionLocalOf { StringsEn }

internal val strings: LocalizedStrings
    @Composable
    @ReadOnlyComposable
    get() = LocalStrings.current

@Composable
internal fun ProvideLocalizedStrings(
    languageMode: LanguageMode,
    content: @Composable () -> Unit,
) {
    CompositionLocalProvider(
        LocalStrings provides stringsFor(resolveAppLanguage(languageMode, systemLanguageTag())),
        content = content,
    )
}

private fun stringsFor(language: AppLanguage): LocalizedStrings = when (language) {
    AppLanguage.English -> StringsEn
    AppLanguage.Chinese -> StringsZh
    AppLanguage.Korean -> StringsKo
    AppLanguage.Japanese -> StringsJa
    AppLanguage.French -> StringsFr
    AppLanguage.Spanish -> StringsEs
}

private val StringsEn = LocalizedStrings(
    language = AppLanguage.English,
    drive = "Drive",
    review = "Review",
    settings = "Settings",
    units = "Units",
    locationSource = "Location source",
    phoneGps = "Phone GPS",
    simulated = "Simulated",
    locationLockedWhileTiming = "Location source is locked while timing is active.",
    phoneGpsUnavailable = "Phone GPS is not wired on this platform yet.",
    phoneGpsPermissionRequired = "Allow location permission to use Phone GPS.",
    highRateGnss = "High-rate GNSS",
    highRateGnssSupporting = "Raw phone GPS for faster fixes and satellite/L5 quality. Applies on the next feed start.",
    externalGnss = "External GNSS",
    externalGnssUnvalidatedNote = "Protocol preview (NMEA 0183) — connection behavior is not validated against real receiver hardware yet.",
    theme = "Theme",
    themeSystem = "System",
    themeDark = "Dark",
    themeLight = "Light",
    languageTitle = "Language",
    languageSystem = "System",
    glasses = "Glasses",
    registerPair = "Register / Pair",
    castToGlasses = "Cast to glasses",
    glassesReconnecting = "Glasses reconnecting…",
    glassesPage = "Glasses page",
    glassesOff = "Off",
    hudDeltaOnly = "Delta",
    hudFocused = "Focused",
    hudTelemetry = "Telemetry",
    noGlassesDevices = "No glasses found",
    noGlassesSelected = "Select glasses in Settings first",
    displayCapable = "Display",
    displayUnsupported = "No display",
    firmwareUpdateRequired = "Firmware update required",
    glassesAppUpdateRequired = "Glasses app update required",
    openFirmwareUpdate = "Open firmware update",
    openGlassesAppUpdate = "Open glasses app update",
    glassesIdle = "Not connected",
    glassesConnecting = "Connecting",
    glassesConnected = "Connected",
    whileTiming = "While timing",
    fullscreenWhileTiming = "Fullscreen while timing",
    keepScreenAwakeWhileTiming = "Keep screen awake while timing",
    dashReadouts = "Dash readouts",
    speedTrace = "Speed trace",
    gpsDiagnostics = "GPS diagnostics",
    safetySettings = "Closed-course/private-track use only. Configure the display while stationary.",
    sessions = "Sessions",
    tracks = "Tracks",
    rawCaptures = "Raw captures",
    archivedTracks = "Archived tracks",
    noSavedSessionsYet = "No saved sessions yet",
    emptyReviewText = "Mark a track, then start a timing session. Saved tracks and sessions show up here.",
    best = "BEST",
    sessionEntry = "Session",
    trackEntry = "Track",
    rawCaptureEntry = "Raw capture",
    untitled = "Untitled",
    unfinishedSessionFound = "Unfinished session found",
    unfinishedSessionText = "You have a session that wasn't saved.",
    discardUnfinishedTitle = "Discard unfinished session?",
    discardUnfinishedText = "Discard unfinished session? Recorded data will be lost.",
    resume = "Resume",
    save = "Save",
    saveSession = "Save Session",
    savingSession = "Saving...",
    discard = "Discard",
    discardSession = "Discard session",
    tapAgainDiscardSession = "Tap again to discard session",
    cancel = "Cancel",
    close = "Close",
    checkSelectedTrack = "Check selected track",
    stillUseThisTrack = "Still use this track",
    chooseAnotherTrack = "Choose another track",
    sessionEnded = "Session ended",
    sessionSaved = "Session saved",
    startTiming = "Start Timing",
    stopTiming = "Stop timing",
    stopMarking = "Stop marking",
    stopRawRecording = "Stop raw recording",
    recordRawGpsDiagnostic = "Record raw GPS (diagnostic)",
    rawGpsRecordingShort = "Recording raw GPS for diagnosis.",
    rawGpsRecordingLong = "Recording raw GPS for diagnosis. No lap timing is running.",
    markingGuidance = "Record one complete course pass, then stop marking.",
    waitingForFirstGpsFix = "Waiting for the first GPS fix...",
    markingTime = "MARKING TIME",
    points = "POINTS",
    chooseTrack = "Choose track",
    newTrack = "New Track",
    noTrackSelected = "No track selected",
    pickSavedTrack = "Pick a saved track to start timing.",
    markFirstTrack = "Choose a course type, then record one complete pass.",
    noSavedTracksYet = "No saved tracks yet.",
    track = "TRACK",
    current = "Current",
    needsStartFinishBeforeTiming = "Needs start/finish before timing",
    direction = "DIRECTION",
    courseType = "COURSE",
    circuit = "Circuit",
    pointToPoint = "Point-to-point",
    recorded = "Recorded",
    reverse = "Reverse",
    switchToLandscape = "Switch to landscape",
    switchToPortrait = "Switch to portrait",
    closeTrackPicker = "Close track picker",
    trackReview = "Track Review",
    reRecordTrack = "Re-record",
    reRecordTrackTitle = "Re-record track?",
    reRecordTrackText = "Re-record track? The current marking trace and reference line will be replaced.",
    trackName = "Track name",
    retry = "Retry",
    discardTrack = "Discard track",
    discardTrackTitle = "Discard track?",
    discardTrackText = "Discard this track? You'll lose the marking trace and reference line.",
    saveTrack = "Save track",
    cleanLoopsCaptured = "clean loops captured",
    startFinishSet = "Start/finish is set.",
    savingPlacesStartFinish = "Saving places the start/finish at the recorded start. Adjustable later in the course editor.",
    failedCaptureStatus = "Couldn't build the course. Re-record one complete pass with a clear GPS trace.",
    noLapTimesYet = "No lap times yet",
    noLapTimesNote = "Marking capture does not produce lap times.",
    captureDetails = "Capture details",
    loops = "Loops",
    detected = "detected",
    accepted = "accepted",
    rejected = "rejected",
    samples = "Samples",
    degraded = "degraded",
    phoneGpsLive = "Phone GPS live",
    demoSimGps = "Demo sim GPS",
    replay = "Replay",
    pauseReplay = "Pause replay",
    restartReplay = "Restart replay",
    exportJson = "Export JSON",
    exportGpx = "Export GPX",
    archive = "Archive",
    archived = "Archived",
    restore = "Restore",
    delete = "Delete",
    deleteReviewItemText = "This permanently removes the selected item from this device.",
    rename = "Rename",
    duplicate = "Duplicate",
    edit = "Edit",
    setCurrent = "Set current",
    sectorTiming = "Sector timing",
    readyToSave = "Ready to save",
    tapTraceToPlaceStartFinish = "Tap the trace to place start/finish.",
    cancelEditing = "Cancel editing",
)

private val StringsZh = LocalizedStrings(
    language = AppLanguage.Chinese,
    drive = "驾驶",
    review = "回顾",
    settings = "设置",
    units = "单位",
    locationSource = "定位来源",
    phoneGps = "手机 GPS",
    simulated = "模拟",
    locationLockedWhileTiming = "计时进行中不能切换定位来源。",
    phoneGpsUnavailable = "此平台暂未接入手机 GPS。",
    phoneGpsPermissionRequired = "请允许定位权限以使用手机 GPS。",
    highRateGnss = "高频 GNSS",
    highRateGnssSupporting = "使用原始手机 GPS 以获得更快定位和卫星/L5 质量信息。下次启动数据源时生效。",
    externalGnss = "外部 GNSS",
    externalGnssUnvalidatedNote = "协议预览版（NMEA 0183）——尚未通过真实接收器硬件验证连接行为。",
    theme = "主题",
    themeSystem = "跟随系统",
    themeDark = "深色",
    themeLight = "浅色",
    languageTitle = "语言",
    languageSystem = "跟随系统",
    glasses = "眼镜",
    registerPair = "注册 / 配对",
    castToGlasses = "投射到眼镜",
    glassesReconnecting = "眼镜正在重连…",
    glassesPage = "眼镜页面",
    glassesOff = "关闭",
    hudDeltaOnly = "Delta",
    hudFocused = "专注",
    hudTelemetry = "遥测",
    noGlassesDevices = "未发现眼镜",
    noGlassesSelected = "请先在设置中选择眼镜",
    displayCapable = "支持显示",
    displayUnsupported = "不支持显示",
    firmwareUpdateRequired = "需要固件更新",
    glassesAppUpdateRequired = "需要更新眼镜应用",
    openFirmwareUpdate = "打开固件更新",
    openGlassesAppUpdate = "打开眼镜应用更新",
    glassesIdle = "未连接",
    glassesConnecting = "正在连接",
    glassesConnected = "已连接",
    whileTiming = "计时中",
    fullscreenWhileTiming = "计时中全屏",
    keepScreenAwakeWhileTiming = "计时中保持屏幕常亮",
    dashReadouts = "仪表读数",
    speedTrace = "速度曲线",
    gpsDiagnostics = "GPS 诊断",
    safetySettings = "仅限封闭赛道/私人场地使用。请在静止时调整显示设置。",
    sessions = "计时",
    tracks = "赛道",
    rawCaptures = "原始记录",
    archivedTracks = "已归档赛道",
    noSavedSessionsYet = "还没有保存的计时",
    emptyReviewText = "先标记赛道，然后开始计时。保存的赛道和计时会显示在这里。",
    best = "最佳",
    sessionEntry = "计时",
    trackEntry = "赛道",
    rawCaptureEntry = "原始记录",
    untitled = "未命名",
    unfinishedSessionFound = "发现未完成的计时",
    unfinishedSessionText = "有一段计时尚未保存。",
    discardUnfinishedTitle = "丢弃未完成计时？",
    discardUnfinishedText = "丢弃未完成计时？已记录的数据将会丢失。",
    resume = "继续",
    save = "保存",
    saveSession = "保存计时",
    savingSession = "保存中...",
    discard = "丢弃",
    discardSession = "丢弃计时",
    tapAgainDiscardSession = "再次点按丢弃计时",
    cancel = "取消",
    close = "关闭",
    checkSelectedTrack = "检查所选赛道",
    stillUseThisTrack = "仍使用此赛道",
    chooseAnotherTrack = "选择其他赛道",
    sessionEnded = "计时已结束",
    sessionSaved = "计时已保存",
    startTiming = "开始计时",
    stopTiming = "停止计时",
    stopMarking = "停止标记",
    stopRawRecording = "停止原始记录",
    recordRawGpsDiagnostic = "记录原始 GPS（诊断）",
    rawGpsRecordingShort = "正在记录原始 GPS 用于诊断。",
    rawGpsRecordingLong = "正在记录原始 GPS 用于诊断。圈速计时未运行。",
    markingGuidance = "完整记录一次路线后即可停止标记。",
    waitingForFirstGpsFix = "等待第一次 GPS 定位...",
    markingTime = "标记时间",
    points = "点数",
    chooseTrack = "选择赛道",
    newTrack = "新赛道",
    noTrackSelected = "未选择赛道",
    pickSavedTrack = "选择已保存赛道以开始计时。",
    markFirstTrack = "先选择路线类型，然后完整记录一次路线。",
    noSavedTracksYet = "还没有保存的赛道。",
    track = "赛道",
    current = "当前",
    needsStartFinishBeforeTiming = "计时前需要设置起终点",
    direction = "方向",
    courseType = "路线",
    circuit = "闭合赛道",
    pointToPoint = "开放赛道",
    recorded = "记录方向",
    reverse = "反向",
    switchToLandscape = "切换到横屏",
    switchToPortrait = "切换到竖屏",
    closeTrackPicker = "关闭赛道选择器",
    trackReview = "赛道回顾",
    reRecordTrack = "重新记录",
    reRecordTrackTitle = "重新记录赛道？",
    reRecordTrackText = "重新记录赛道？当前标记轨迹和参考线将被替换。",
    trackName = "赛道名称",
    retry = "重试",
    discardTrack = "丢弃赛道",
    discardTrackTitle = "丢弃赛道？",
    discardTrackText = "丢弃这条赛道？你将失去标记轨迹和参考线。",
    saveTrack = "保存赛道",
    cleanLoopsCaptured = "个干净圈已捕获",
    startFinishSet = "起终点已设置。",
    savingPlacesStartFinish = "保存时会把起终点放在记录开始处，之后可在赛道编辑器中调整。",
    failedCaptureStatus = "无法生成赛道。请重新记录一次清晰、完整的 GPS 轨迹。",
    noLapTimesYet = "暂无圈速",
    noLapTimesNote = "赛道标记不会生成圈速。",
    captureDetails = "捕获详情",
    loops = "圈",
    detected = "检测",
    accepted = "接受",
    rejected = "拒绝",
    samples = "采样",
    degraded = "降级",
    phoneGpsLive = "手机 GPS 实时",
    demoSimGps = "演示模拟 GPS",
    replay = "回放",
    pauseReplay = "暂停回放",
    restartReplay = "重新回放",
    exportJson = "导出 JSON",
    exportGpx = "导出 GPX",
    archive = "归档",
    archived = "已归档",
    restore = "恢复",
    delete = "删除",
    deleteReviewItemText = "这会从本机永久删除所选项目。",
    rename = "重命名",
    duplicate = "复制",
    edit = "编辑",
    setCurrent = "设为当前",
    sectorTiming = "分段计时",
    readyToSave = "可保存",
    tapTraceToPlaceStartFinish = "点按轨迹以放置起终点。",
    cancelEditing = "取消编辑",
)

private val StringsKo = LocalizedStrings(
    language = AppLanguage.Korean,
    drive = "주행",
    review = "리뷰",
    settings = "설정",
    units = "단위",
    locationSource = "위치 소스",
    phoneGps = "휴대폰 GPS",
    simulated = "시뮬레이션",
    locationLockedWhileTiming = "계시 중에는 위치 소스를 바꿀 수 없습니다.",
    phoneGpsUnavailable = "이 플랫폼에는 아직 휴대폰 GPS가 연결되지 않았습니다.",
    phoneGpsPermissionRequired = "휴대폰 GPS를 사용하려면 위치 권한을 허용하세요.",
    highRateGnss = "고주기 GNSS",
    highRateGnssSupporting = "더 빠른 위치 갱신과 위성/L5 품질 정보를 위해 원시 휴대폰 GPS를 사용합니다. 다음 피드 시작부터 적용됩니다.",
    externalGnss = "외부 GNSS",
    externalGnssUnvalidatedNote = "프로토콜 미리보기(NMEA 0183) — 실제 수신기 하드웨어로 연결 동작이 아직 검증되지 않았습니다.",
    theme = "테마",
    themeSystem = "시스템",
    themeDark = "어둡게",
    themeLight = "밝게",
    languageTitle = "언어",
    languageSystem = "시스템",
    glasses = "안경",
    registerPair = "등록 / 페어링",
    castToGlasses = "안경으로 전송",
    glassesReconnecting = "안경 재연결 중…",
    glassesPage = "안경 화면",
    glassesOff = "끄기",
    hudDeltaOnly = "델타",
    hudFocused = "집중",
    hudTelemetry = "텔레메트리",
    noGlassesDevices = "안경을 찾을 수 없음",
    noGlassesSelected = "설정에서 안경을 먼저 선택하세요",
    displayCapable = "디스플레이",
    displayUnsupported = "디스플레이 없음",
    firmwareUpdateRequired = "펌웨어 업데이트 필요",
    glassesAppUpdateRequired = "안경 앱 업데이트 필요",
    openFirmwareUpdate = "펌웨어 업데이트 열기",
    openGlassesAppUpdate = "안경 앱 업데이트 열기",
    glassesIdle = "연결 안 됨",
    glassesConnecting = "연결 중",
    glassesConnected = "연결됨",
    whileTiming = "계시 중",
    fullscreenWhileTiming = "계시 중 전체 화면",
    keepScreenAwakeWhileTiming = "계시 중 화면 켜짐 유지",
    dashReadouts = "대시 표시",
    speedTrace = "속도 그래프",
    gpsDiagnostics = "GPS 진단",
    safetySettings = "폐쇄 코스/사유 트랙에서만 사용하세요. 표시 설정은 정지 상태에서 조정하세요.",
    sessions = "세션",
    tracks = "트랙",
    rawCaptures = "원시 캡처",
    archivedTracks = "보관된 트랙",
    noSavedSessionsYet = "저장된 세션이 없습니다",
    emptyReviewText = "트랙을 마킹한 뒤 계시 세션을 시작하세요. 저장된 트랙과 세션이 여기에 표시됩니다.",
    best = "베스트",
    sessionEntry = "세션",
    trackEntry = "트랙",
    rawCaptureEntry = "원시 캡처",
    untitled = "제목 없음",
    unfinishedSessionFound = "완료되지 않은 세션 발견",
    unfinishedSessionText = "저장되지 않은 세션이 있습니다.",
    discardUnfinishedTitle = "완료되지 않은 세션을 폐기할까요?",
    discardUnfinishedText = "완료되지 않은 세션을 폐기할까요? 기록된 데이터가 사라집니다.",
    resume = "재개",
    save = "저장",
    saveSession = "세션 저장",
    savingSession = "저장 중...",
    discard = "폐기",
    discardSession = "세션 폐기",
    tapAgainDiscardSession = "다시 눌러 세션 폐기",
    cancel = "취소",
    close = "닫기",
    checkSelectedTrack = "선택한 트랙 확인",
    stillUseThisTrack = "이 트랙 사용",
    chooseAnotherTrack = "다른 트랙 선택",
    sessionEnded = "세션 종료",
    sessionSaved = "세션 저장됨",
    startTiming = "계시 시작",
    stopTiming = "계시 중지",
    stopMarking = "마킹 중지",
    stopRawRecording = "원시 기록 중지",
    recordRawGpsDiagnostic = "원시 GPS 기록(진단)",
    rawGpsRecordingShort = "진단용 원시 GPS를 기록 중입니다.",
    rawGpsRecordingLong = "진단용 원시 GPS를 기록 중입니다. 랩 계시는 실행 중이 아닙니다.",
    markingGuidance = "코스 한 번을 완전히 기록한 뒤 마킹을 중지하세요.",
    waitingForFirstGpsFix = "첫 GPS 위치를 기다리는 중...",
    markingTime = "마킹 시간",
    points = "포인트",
    chooseTrack = "트랙 선택",
    newTrack = "새 트랙",
    noTrackSelected = "선택한 트랙 없음",
    pickSavedTrack = "저장된 트랙을 선택해 계시를 시작하세요.",
    markFirstTrack = "코스 유형을 선택한 뒤 한 번 완전히 기록하세요.",
    noSavedTracksYet = "저장된 트랙이 없습니다.",
    track = "트랙",
    current = "현재",
    needsStartFinishBeforeTiming = "계시 전 스타트/피니시가 필요합니다",
    direction = "방향",
    courseType = "코스",
    circuit = "서킷",
    pointToPoint = "포인트 투 포인트",
    recorded = "기록 방향",
    reverse = "역방향",
    switchToLandscape = "가로 화면으로 전환",
    switchToPortrait = "세로 화면으로 전환",
    closeTrackPicker = "트랙 선택기 닫기",
    trackReview = "트랙 리뷰",
    reRecordTrack = "다시 기록",
    reRecordTrackTitle = "트랙을 다시 기록할까요?",
    reRecordTrackText = "트랙을 다시 기록할까요? 현재 마킹 트레이스와 기준선이 교체됩니다.",
    trackName = "트랙 이름",
    retry = "다시 시도",
    discardTrack = "트랙 폐기",
    discardTrackTitle = "트랙을 폐기할까요?",
    discardTrackText = "이 트랙을 폐기할까요? 마킹 트레이스와 기준선을 잃게 됩니다.",
    saveTrack = "트랙 저장",
    cleanLoopsCaptured = "개의 깨끗한 랩 캡처됨",
    startFinishSet = "스타트/피니시가 설정되었습니다.",
    savingPlacesStartFinish = "저장하면 기록 시작 지점에 스타트/피니시가 배치됩니다. 나중에 코스 편집기에서 조정할 수 있습니다.",
    failedCaptureStatus = "코스를 만들 수 없습니다. 선명한 GPS 트레이스로 한 번 완전히 다시 기록하세요.",
    noLapTimesYet = "랩 타임 없음",
    noLapTimesNote = "트랙 마킹은 랩 타임을 만들지 않습니다.",
    captureDetails = "캡처 세부 정보",
    loops = "랩",
    detected = "감지",
    accepted = "승인",
    rejected = "거부",
    samples = "샘플",
    degraded = "저하",
    phoneGpsLive = "휴대폰 GPS 실시간",
    demoSimGps = "데모 시뮬레이션 GPS",
    replay = "리플레이",
    pauseReplay = "리플레이 일시정지",
    restartReplay = "리플레이 재시작",
    exportJson = "JSON 내보내기",
    exportGpx = "GPX 내보내기",
    archive = "보관",
    archived = "보관됨",
    restore = "복원",
    delete = "삭제",
    deleteReviewItemText = "선택한 항목을 이 기기에서 영구 삭제합니다.",
    rename = "이름 변경",
    duplicate = "복제",
    edit = "편집",
    setCurrent = "현재로 설정",
    sectorTiming = "섹터 계시",
    readyToSave = "저장 가능",
    tapTraceToPlaceStartFinish = "트레이스를 탭해 스타트/피니시를 배치하세요.",
    cancelEditing = "편집 취소",
)

private val StringsJa = LocalizedStrings(
    language = AppLanguage.Japanese,
    drive = "走行",
    review = "レビュー",
    settings = "設定",
    units = "単位",
    locationSource = "位置情報ソース",
    phoneGps = "スマホ GPS",
    simulated = "シミュレーション",
    locationLockedWhileTiming = "計測中は位置情報ソースを変更できません。",
    phoneGpsUnavailable = "このプラットフォームではスマホ GPS がまだ接続されていません。",
    phoneGpsPermissionRequired = "スマホ GPS を使うには位置情報の許可が必要です。",
    highRateGnss = "高頻度 GNSS",
    highRateGnssSupporting = "より速い測位と衛星/L5 品質情報のために生のスマホ GPS を使います。次回のフィード開始時に反映されます。",
    externalGnss = "外部 GNSS",
    externalGnssUnvalidatedNote = "プロトコルプレビュー（NMEA 0183）— 実機受信機での接続動作はまだ検証されていません。",
    theme = "テーマ",
    themeSystem = "システム",
    themeDark = "ダーク",
    themeLight = "ライト",
    languageTitle = "言語",
    languageSystem = "システム",
    glasses = "グラス",
    registerPair = "登録 / ペアリング",
    castToGlasses = "グラスへ送信",
    glassesReconnecting = "グラスを再接続中…",
    glassesPage = "グラス表示",
    glassesOff = "オフ",
    hudDeltaOnly = "デルタ",
    hudFocused = "集中",
    hudTelemetry = "テレメトリー",
    noGlassesDevices = "グラスが見つかりません",
    noGlassesSelected = "先に設定でグラスを選択",
    displayCapable = "表示対応",
    displayUnsupported = "表示非対応",
    firmwareUpdateRequired = "ファームウェア更新が必要",
    glassesAppUpdateRequired = "グラスアプリ更新が必要",
    openFirmwareUpdate = "ファームウェア更新を開く",
    openGlassesAppUpdate = "グラスアプリ更新を開く",
    glassesIdle = "未接続",
    glassesConnecting = "接続中",
    glassesConnected = "接続済み",
    whileTiming = "計測中",
    fullscreenWhileTiming = "計測中は全画面",
    keepScreenAwakeWhileTiming = "計測中は画面を常時点灯",
    dashReadouts = "ダッシュ表示",
    speedTrace = "速度トレース",
    gpsDiagnostics = "GPS 診断",
    safetySettings = "閉鎖コース/私有トラックでのみ使用してください。表示設定は停止中に行ってください。",
    sessions = "セッション",
    tracks = "トラック",
    rawCaptures = "生キャプチャ",
    archivedTracks = "アーカイブ済みトラック",
    noSavedSessionsYet = "保存済みセッションはありません",
    emptyReviewText = "トラックをマーキングしてから計測セッションを開始してください。保存済みトラックとセッションがここに表示されます。",
    best = "ベスト",
    sessionEntry = "セッション",
    trackEntry = "トラック",
    rawCaptureEntry = "生キャプチャ",
    untitled = "無題",
    unfinishedSessionFound = "未完了のセッションがあります",
    unfinishedSessionText = "保存されていないセッションがあります。",
    discardUnfinishedTitle = "未完了セッションを破棄しますか？",
    discardUnfinishedText = "未完了セッションを破棄しますか？記録データは失われます。",
    resume = "再開",
    save = "保存",
    saveSession = "セッション保存",
    savingSession = "保存中...",
    discard = "破棄",
    discardSession = "セッション破棄",
    tapAgainDiscardSession = "もう一度押して破棄",
    cancel = "キャンセル",
    close = "閉じる",
    checkSelectedTrack = "選択中のトラックを確認",
    stillUseThisTrack = "このトラックを使う",
    chooseAnotherTrack = "別のトラックを選択",
    sessionEnded = "セッション終了",
    sessionSaved = "セッションを保存しました",
    startTiming = "計測開始",
    stopTiming = "計測停止",
    stopMarking = "マーキング停止",
    stopRawRecording = "生データ記録停止",
    recordRawGpsDiagnostic = "生 GPS を記録(診断)",
    rawGpsRecordingShort = "診断用の生 GPS を記録中です。",
    rawGpsRecordingLong = "診断用の生 GPS を記録中です。ラップ計測は実行されていません。",
    markingGuidance = "コースを1回完全に記録したらマーキングを停止できます。",
    waitingForFirstGpsFix = "最初の GPS 測位を待っています...",
    markingTime = "マーキング時間",
    points = "ポイント",
    chooseTrack = "トラック選択",
    newTrack = "新規トラック",
    noTrackSelected = "トラック未選択",
    pickSavedTrack = "保存済みトラックを選んで計測を開始します。",
    markFirstTrack = "コース種別を選び、1回完全に記録してください。",
    noSavedTracksYet = "保存済みトラックはありません。",
    track = "トラック",
    current = "現在",
    needsStartFinishBeforeTiming = "計測前にスタート/フィニッシュが必要です",
    direction = "方向",
    courseType = "コース",
    circuit = "周回",
    pointToPoint = "ポイント間",
    recorded = "記録方向",
    reverse = "逆方向",
    switchToLandscape = "横向きに切り替え",
    switchToPortrait = "縦向きに切り替え",
    closeTrackPicker = "トラック選択を閉じる",
    trackReview = "トラックレビュー",
    reRecordTrack = "再記録",
    reRecordTrackTitle = "トラックを再記録しますか？",
    reRecordTrackText = "トラックを再記録しますか？現在のマーキングトレースと基準線は置き換えられます。",
    trackName = "トラック名",
    retry = "再試行",
    discardTrack = "トラック破棄",
    discardTrackTitle = "トラックを破棄しますか？",
    discardTrackText = "このトラックを破棄しますか？マーキングトレースと基準線は失われます。",
    saveTrack = "トラック保存",
    cleanLoopsCaptured = "件のクリーンな周回を取得",
    startFinishSet = "スタート/フィニッシュが設定されています。",
    savingPlacesStartFinish = "保存すると記録開始位置にスタート/フィニッシュを配置します。後でコースエディタで調整できます。",
    failedCaptureStatus = "コースを作成できませんでした。明確な GPS トレースで1回完全に再記録してください。",
    noLapTimesYet = "ラップタイムなし",
    noLapTimesNote = "トラックマーキングではラップタイムは生成されません。",
    captureDetails = "キャプチャ詳細",
    loops = "周回",
    detected = "検出",
    accepted = "採用",
    rejected = "除外",
    samples = "サンプル",
    degraded = "低品質",
    phoneGpsLive = "スマホ GPS ライブ",
    demoSimGps = "デモシミュレーション GPS",
    replay = "リプレイ",
    pauseReplay = "リプレイ一時停止",
    restartReplay = "リプレイ再開",
    exportJson = "JSON 書き出し",
    exportGpx = "GPX 書き出し",
    archive = "アーカイブ",
    archived = "アーカイブ済み",
    restore = "復元",
    delete = "削除",
    deleteReviewItemText = "選択した項目をこのデバイスから完全に削除します。",
    rename = "名前変更",
    duplicate = "複製",
    edit = "編集",
    setCurrent = "現在に設定",
    sectorTiming = "セクター計測",
    readyToSave = "保存できます",
    tapTraceToPlaceStartFinish = "トレースをタップしてスタート/フィニッシュを配置します。",
    cancelEditing = "編集をキャンセル",
)

private val StringsFr = LocalizedStrings(
    language = AppLanguage.French,
    drive = "Pilotage",
    review = "Review",
    settings = "Réglages",
    units = "Unités",
    locationSource = "Source de position",
    phoneGps = "GPS du téléphone",
    simulated = "Simulé",
    locationLockedWhileTiming = "La source de position est verrouillée pendant le chronométrage.",
    phoneGpsUnavailable = "Le GPS du téléphone n'est pas encore branché sur cette plateforme.",
    phoneGpsPermissionRequired = "Autorisez la position pour utiliser le GPS du téléphone.",
    highRateGnss = "GNSS haute fréquence",
    highRateGnssSupporting = "GPS brut du téléphone pour des points plus rapides et la qualité satellite/L5. S'applique au prochain démarrage du flux.",
    externalGnss = "GNSS externe",
    externalGnssUnvalidatedNote = "Aperçu de protocole (NMEA 0183) — le comportement de connexion n'est pas encore validé avec un vrai récepteur.",
    theme = "Thème",
    themeSystem = "Système",
    themeDark = "Sombre",
    themeLight = "Clair",
    languageTitle = "Langue",
    languageSystem = "Système",
    glasses = "Lunettes",
    registerPair = "Enregistrer / associer",
    castToGlasses = "Diffuser aux lunettes",
    glassesReconnecting = "Reconnexion des lunettes…",
    glassesPage = "Page lunettes",
    glassesOff = "Arrêt",
    hudDeltaOnly = "Delta",
    hudFocused = "Focus",
    hudTelemetry = "Télémétrie",
    noGlassesDevices = "Aucune lunette détectée",
    noGlassesSelected = "Choisissez des lunettes dans Réglages",
    displayCapable = "Affichage",
    displayUnsupported = "Sans affichage",
    firmwareUpdateRequired = "Mise à jour du firmware requise",
    glassesAppUpdateRequired = "Mise à jour de l'app lunettes requise",
    openFirmwareUpdate = "Ouvrir la mise à jour firmware",
    openGlassesAppUpdate = "Ouvrir la mise à jour app lunettes",
    glassesIdle = "Non connecté",
    glassesConnecting = "Connexion",
    glassesConnected = "Connecté",
    whileTiming = "Pendant le chrono",
    fullscreenWhileTiming = "Plein écran pendant le chrono",
    keepScreenAwakeWhileTiming = "Garder l'écran allumé pendant le chrono",
    dashReadouts = "Affichages du tableau",
    speedTrace = "Trace de vitesse",
    gpsDiagnostics = "Diagnostics GPS",
    safetySettings = "Usage sur circuit fermé/terrain privé uniquement. Réglez l'affichage à l'arrêt.",
    sessions = "Sessions",
    tracks = "Circuits",
    rawCaptures = "Captures brutes",
    archivedTracks = "Circuits archivés",
    noSavedSessionsYet = "Aucune session enregistrée",
    emptyReviewText = "Marquez un circuit, puis démarrez une session chrono. Les circuits et sessions enregistrés apparaissent ici.",
    best = "MEILLEUR",
    sessionEntry = "Session",
    trackEntry = "Circuit",
    rawCaptureEntry = "Capture brute",
    untitled = "Sans titre",
    unfinishedSessionFound = "Session non terminée trouvée",
    unfinishedSessionText = "Une session n'a pas été enregistrée.",
    discardUnfinishedTitle = "Supprimer la session non terminée ?",
    discardUnfinishedText = "Supprimer la session non terminée ? Les données enregistrées seront perdues.",
    resume = "Reprendre",
    save = "Enregistrer",
    saveSession = "Enregistrer la session",
    savingSession = "Enregistrement...",
    discard = "Supprimer",
    discardSession = "Supprimer la session",
    tapAgainDiscardSession = "Touchez encore pour supprimer",
    cancel = "Annuler",
    close = "Fermer",
    checkSelectedTrack = "Vérifier le circuit sélectionné",
    stillUseThisTrack = "Utiliser ce circuit",
    chooseAnotherTrack = "Choisir un autre circuit",
    sessionEnded = "Session terminée",
    sessionSaved = "Session enregistrée",
    startTiming = "Démarrer le chrono",
    stopTiming = "Arrêter le chrono",
    stopMarking = "Arrêter le marquage",
    stopRawRecording = "Arrêter l'enregistrement brut",
    recordRawGpsDiagnostic = "Enregistrer le GPS brut (diagnostic)",
    rawGpsRecordingShort = "Enregistrement du GPS brut pour diagnostic.",
    rawGpsRecordingLong = "Enregistrement du GPS brut pour diagnostic. Aucun chrono au tour n'est en cours.",
    markingGuidance = "Enregistrez un passage complet, puis arrêtez le marquage.",
    waitingForFirstGpsFix = "Attente du premier point GPS...",
    markingTime = "TEMPS DE MARQUAGE",
    points = "POINTS",
    chooseTrack = "Choisir un circuit",
    newTrack = "Nouveau circuit",
    noTrackSelected = "Aucun circuit sélectionné",
    pickSavedTrack = "Choisissez un circuit enregistré pour démarrer le chrono.",
    markFirstTrack = "Choisissez un type de parcours, puis enregistrez un passage complet.",
    noSavedTracksYet = "Aucun circuit enregistré.",
    track = "CIRCUIT",
    current = "Actuel",
    needsStartFinishBeforeTiming = "Départ/arrivée requis avant le chrono",
    direction = "DIRECTION",
    courseType = "PARCOURS",
    circuit = "Circuit",
    pointToPoint = "Point à point",
    recorded = "Enregistré",
    reverse = "Inverse",
    switchToLandscape = "Passer en paysage",
    switchToPortrait = "Passer en portrait",
    closeTrackPicker = "Fermer le sélecteur de circuit",
    trackReview = "Review du circuit",
    reRecordTrack = "Réenregistrer",
    reRecordTrackTitle = "Réenregistrer le circuit ?",
    reRecordTrackText = "Réenregistrer le circuit ? La trace de marquage et la ligne de référence actuelles seront remplacées.",
    trackName = "Nom du circuit",
    retry = "Réessayer",
    discardTrack = "Supprimer le circuit",
    discardTrackTitle = "Supprimer le circuit ?",
    discardTrackText = "Supprimer ce circuit ? Vous perdrez la trace de marquage et la ligne de référence.",
    saveTrack = "Enregistrer le circuit",
    cleanLoopsCaptured = "tours propres capturés",
    startFinishSet = "Le départ/arrivée est défini.",
    savingPlacesStartFinish = "L'enregistrement place le départ/arrivée au début enregistré. Ajustable plus tard dans l'éditeur de circuit.",
    failedCaptureStatus = "Impossible de construire le parcours. Réenregistrez un passage complet avec une trace GPS claire.",
    noLapTimesYet = "Aucun temps au tour",
    noLapTimesNote = "Le marquage du circuit ne produit pas de temps au tour.",
    captureDetails = "Détails de capture",
    loops = "Tours",
    detected = "détectés",
    accepted = "acceptés",
    rejected = "rejetés",
    samples = "Échantillons",
    degraded = "dégradés",
    phoneGpsLive = "GPS téléphone en direct",
    demoSimGps = "GPS simulé de démo",
    replay = "Relecture",
    pauseReplay = "Mettre la relecture en pause",
    restartReplay = "Relancer la relecture",
    exportJson = "Exporter JSON",
    exportGpx = "Exporter GPX",
    archive = "Archiver",
    archived = "Archivé",
    restore = "Restaurer",
    delete = "Supprimer",
    deleteReviewItemText = "Supprime définitivement l'élément sélectionné de cet appareil.",
    rename = "Renommer",
    duplicate = "Dupliquer",
    edit = "Modifier",
    setCurrent = "Définir actuel",
    sectorTiming = "Chrono par secteur",
    readyToSave = "Prêt à enregistrer",
    tapTraceToPlaceStartFinish = "Touchez la trace pour placer départ/arrivée.",
    cancelEditing = "Annuler l'édition",
)

private val StringsEs = LocalizedStrings(
    language = AppLanguage.Spanish,
    drive = "Conducir",
    review = "Revisión",
    settings = "Ajustes",
    units = "Unidades",
    locationSource = "Fuente de ubicación",
    phoneGps = "GPS del teléfono",
    simulated = "Simulado",
    locationLockedWhileTiming = "La fuente de ubicación está bloqueada mientras corre el cronómetro.",
    phoneGpsUnavailable = "El GPS del teléfono todavía no está conectado en esta plataforma.",
    phoneGpsPermissionRequired = "Permite la ubicación para usar el GPS del teléfono.",
    highRateGnss = "GNSS de alta frecuencia",
    highRateGnssSupporting = "GPS bruto del teléfono para actualizaciones más rápidas y calidad satélite/L5. Se aplica al próximo inicio del flujo.",
    externalGnss = "GNSS externo",
    externalGnssUnvalidatedNote = "Vista previa de protocolo (NMEA 0183) — el comportamiento de conexión aún no está validado con hardware receptor real.",
    theme = "Tema",
    themeSystem = "Sistema",
    themeDark = "Oscuro",
    themeLight = "Claro",
    languageTitle = "Idioma",
    languageSystem = "Sistema",
    glasses = "Gafas",
    registerPair = "Registrar / vincular",
    castToGlasses = "Enviar a las gafas",
    glassesReconnecting = "Reconectando gafas…",
    glassesPage = "Vista en gafas",
    glassesOff = "Apagado",
    hudDeltaOnly = "Delta",
    hudFocused = "Enfoque",
    hudTelemetry = "Telemetría",
    noGlassesDevices = "No se encontraron gafas",
    noGlassesSelected = "Selecciona gafas en Ajustes",
    displayCapable = "Pantalla",
    displayUnsupported = "Sin pantalla",
    firmwareUpdateRequired = "Actualización de firmware requerida",
    glassesAppUpdateRequired = "Actualización de app de gafas requerida",
    openFirmwareUpdate = "Abrir actualización de firmware",
    openGlassesAppUpdate = "Abrir actualización de app",
    glassesIdle = "No conectado",
    glassesConnecting = "Conectando",
    glassesConnected = "Conectado",
    whileTiming = "Durante el cronómetro",
    fullscreenWhileTiming = "Pantalla completa durante el cronómetro",
    keepScreenAwakeWhileTiming = "Mantener la pantalla encendida durante el cronómetro",
    dashReadouts = "Lecturas del panel",
    speedTrace = "Traza de velocidad",
    gpsDiagnostics = "Diagnóstico GPS",
    safetySettings = "Solo para circuito cerrado/pista privada. Configura la pantalla estando detenido.",
    sessions = "Sesiones",
    tracks = "Pistas",
    rawCaptures = "Capturas brutas",
    archivedTracks = "Pistas archivadas",
    noSavedSessionsYet = "Aún no hay sesiones guardadas",
    emptyReviewText = "Marca una pista y luego inicia una sesión cronometrada. Las pistas y sesiones guardadas aparecerán aquí.",
    best = "MEJOR",
    sessionEntry = "Sesión",
    trackEntry = "Pista",
    rawCaptureEntry = "Captura bruta",
    untitled = "Sin título",
    unfinishedSessionFound = "Sesión sin terminar encontrada",
    unfinishedSessionText = "Tienes una sesión que no se guardó.",
    discardUnfinishedTitle = "¿Descartar sesión sin terminar?",
    discardUnfinishedText = "¿Descartar sesión sin terminar? Se perderán los datos registrados.",
    resume = "Reanudar",
    save = "Guardar",
    saveSession = "Guardar sesión",
    savingSession = "Guardando...",
    discard = "Descartar",
    discardSession = "Descartar sesión",
    tapAgainDiscardSession = "Toca otra vez para descartar",
    cancel = "Cancelar",
    close = "Cerrar",
    checkSelectedTrack = "Comprobar pista seleccionada",
    stillUseThisTrack = "Usar esta pista",
    chooseAnotherTrack = "Elegir otra pista",
    sessionEnded = "Sesión terminada",
    sessionSaved = "Sesión guardada",
    startTiming = "Iniciar cronómetro",
    stopTiming = "Detener cronómetro",
    stopMarking = "Detener marcado",
    stopRawRecording = "Detener registro bruto",
    recordRawGpsDiagnostic = "Registrar GPS bruto (diagnóstico)",
    rawGpsRecordingShort = "Registrando GPS bruto para diagnóstico.",
    rawGpsRecordingLong = "Registrando GPS bruto para diagnóstico. No hay cronómetro de vueltas en marcha.",
    markingGuidance = "Registra una pasada completa del recorrido y luego detén el marcado.",
    waitingForFirstGpsFix = "Esperando la primera posición GPS...",
    markingTime = "TIEMPO DE MARCADO",
    points = "PUNTOS",
    chooseTrack = "Elegir pista",
    newTrack = "Nueva pista",
    noTrackSelected = "No hay pista seleccionada",
    pickSavedTrack = "Elige una pista guardada para iniciar el cronómetro.",
    markFirstTrack = "Elige un tipo de recorrido y registra una pasada completa.",
    noSavedTracksYet = "Aún no hay pistas guardadas.",
    track = "PISTA",
    current = "Actual",
    needsStartFinishBeforeTiming = "Necesita salida/meta antes de cronometrar",
    direction = "DIRECCIÓN",
    courseType = "RECORRIDO",
    circuit = "Circuito",
    pointToPoint = "Punto a punto",
    recorded = "Grabada",
    reverse = "Invertida",
    switchToLandscape = "Cambiar a horizontal",
    switchToPortrait = "Cambiar a vertical",
    closeTrackPicker = "Cerrar selector de pista",
    trackReview = "Revisión de pista",
    reRecordTrack = "Volver a registrar",
    reRecordTrackTitle = "¿Volver a registrar la pista?",
    reRecordTrackText = "¿Volver a registrar la pista? Se reemplazarán la traza de marcado y la línea de referencia actuales.",
    trackName = "Nombre de pista",
    retry = "Reintentar",
    discardTrack = "Descartar pista",
    discardTrackTitle = "¿Descartar pista?",
    discardTrackText = "¿Descartar esta pista? Perderás la traza de marcado y la línea de referencia.",
    saveTrack = "Guardar pista",
    cleanLoopsCaptured = "vueltas limpias capturadas",
    startFinishSet = "La salida/meta está configurada.",
    savingPlacesStartFinish = "Al guardar se coloca la salida/meta en el inicio registrado. Luego puedes ajustarla en el editor de circuito.",
    failedCaptureStatus = "No se pudo crear el recorrido. Vuelve a registrar una pasada completa con una traza GPS clara.",
    noLapTimesYet = "Sin tiempos de vuelta",
    noLapTimesNote = "El marcado de pista no produce tiempos de vuelta.",
    captureDetails = "Detalles de captura",
    loops = "Vueltas",
    detected = "detectadas",
    accepted = "aceptadas",
    rejected = "rechazadas",
    samples = "Muestras",
    degraded = "degradadas",
    phoneGpsLive = "GPS del teléfono en vivo",
    demoSimGps = "GPS simulado demo",
    replay = "Repetición",
    pauseReplay = "Pausar repetición",
    restartReplay = "Reiniciar repetición",
    exportJson = "Exportar JSON",
    exportGpx = "Exportar GPX",
    archive = "Archivar",
    archived = "Archivada",
    restore = "Restaurar",
    delete = "Eliminar",
    deleteReviewItemText = "Elimina permanentemente el elemento seleccionado de este dispositivo.",
    rename = "Renombrar",
    duplicate = "Duplicar",
    edit = "Editar",
    setCurrent = "Hacer actual",
    sectorTiming = "Crono por sectores",
    readyToSave = "Listo para guardar",
    tapTraceToPlaceStartFinish = "Toca la traza para colocar salida/meta.",
    cancelEditing = "Cancelar edición",
)
